astoilkov/jsblocks

src/query/observable.js
Added check for properties to (the properties from /query/dom.props).
When you look onto the element with the inspector of your browser, the value attribute wil still be the expression.
That behaviour could be confusing for developers, maybe we should add a comment or something like a ``data-bl-{{attributeName}}`` attribute like so:
```javascript
blocks.query({val: blocks.observable('Some Value')});
```
```html
<input value="{{val}}" data-bl-value="Some Value" data-id="1" />
```
Updating the original attribute is not recommend as it can cause missbehaving in some browsers.
What do you think ?
Also 2 derps :sweat_smile: with the github client (Now I'll rollback to the commandline version of git).
=> Fix for #88

src/query/ElementsData.js, src/query/Expression.js
Observables used in expressions will now get stored in 
``elementData.observables`` for garbage collection, before only observables in data-query methods  got stored there.
``ElementData.clear`` now also cleans up the ``javascript observables._expression`` and ``javascript observables._expressionKeys`` objects/arrays.
Fixes #90.
Also corrected a [typo](https://github.com/Kanaye/jsblocks/blob/7db227b583dc164422c183d58ca3bdc386f50788/src/query/ElementsData.js#L126) (Or at least i think it's a typo cause i could not find any case where data has an id property. Correct me if I'm wrong!)
Say if you don't like something with my solution or had something other with the ``elementData.observables`` array in mind.
Have a nice day.
=> Added garbadge collection for observables._expressions. FIxes #90

src/query/observable.js
Observables check for ``set`` and ``get``-functions on the argument and then mark it as a dependency observables.
Models implement that functions but not as expected for dependency-observables.
=> Added check for __Class__ in blocks.observable. Closes #100.

src/node/overrides.js, src/query/VirtualElement.js
Server side attribute expressions did not get transfered to the client, 
so these expressions did not get updated clientside.
To be more clear an example:
```html
<input type="text" data-query="myObservable" />
{{myObservable}}
<input type="text" value="{{myObservable} "/>
```
Found that while trying to find a solution for #40.
=> Fixed bug with server side attribute expression.

src/query/observable.js, test/spec/query/observables.js
Can be so easy :smile:.
As suggested in https://github.com/astoilkov/jsblocks/issues/86#issuecomment-150876200.
Let me know if you have concerns about this.
Btw. this one is also faster then the replacer way as it only get called when needed. Not much faster but faster.
Closes #86.
=> Added toJSON to observable and tests for it.

src/query/Expression.js, src/query/VirtualElement.js, test/spec/query/expressions.js
For details read the message of the first commit :wink:.
If you find an edge case I didn't fix or you don't like something about this solution feel free to say.
Closes #104
=> Updating/Insetring of wrong nodes fixed. Closes #104

src/mvc/Application.js, src/mvc/View.js, src/mvc/bindContext.js
Replaced 'clonePrototype' in 'Application.extend' with 'bindContext'.
Before observables lose there relation to the original observable.
To reproduce this:
* Clone the shopping-example.
* Replace the wrong version from bower with the 0.3.4.
* Start the app (server siede rendering does not matter)
* Try out the search.
=> Moved 'View._bindContext' to src/mv/bindContext.js.

src/query/Expression.js, src/query/VirtualElement.js, src/query/observable.js, src/query/queries.js, test/spec/query/queries.js
Initial problem with not updating attributes in this edgecase is fixed through updating the ``_state`` property of an VirtualElement as long as the property exsits (and changes).
Added call to ``observable.update()`` in array-oservables ``reset()`` function.
Did not find a case where this could break something, correct me if I'm wrong.
Added a function called ``observable._getValue()`` which just returns the value but does not subscribe it to the ``Observer``. I need this for the ``update`` function of the ``options`` data-query.
Also ``observable.update`` now _not_ subscribes observables or to be more correct it creates and drops a new Observer stack.
I couldn't find a case where it breaks something as the call that causes the subsciption is caused by and on already subscribed elements. …
=> Added update function to options-query fixes #74.

src/node/overrides.js, src/query/DomQuery.js, src/query/queries.js, test/spec/query/queries.js
Fixes all issues found in astoilkov/jsblocks-shopping-example#6:
* Bug with 'sidebar'-named Template in Firefox. When the template is an object but nor an element blocks will now try to get elment with the ID passed.
* Implemented server-side rendering of the ``template`` query when passed with a string as id.
Closes astoilkov/jsblocks-shopping-example#6.
=> Fixed some issues with template data-query.

src/query/observable.js
Added check if observable._expressions has current expression and adds it if it not exists.
Fixes #113.
=> Added check if observable._expressions has current expression. Fixes #113.

src/query/DomQuery.js, src/query/VirtualElement.js, src/query/dom.js
Implements checkbox groups and fixes false negative (falsy) select multiple detection.
Here a working example with a built version of it:https://jsfiddle.net/a22gvf9u/
Closes #123
=> Implements checkbox groups and fixes false negative select multple attribute check.

src/query/DomQuery.js, src/query/queries.js
Cloning the __props__ property of contexts to prevent it from being
overwritten e.g. with new Views and changed the order of execution in the
'with'-data-querie to first push the context and then modify it.
This solves the problem that e.g. the ``view``-data-query overrides the ``$view``-property of all views (including none views like the application context).
[Here an example visualising the problem](https://jsfiddle.net/19r7Lsbf/)
I have tested it and thought about if it could have negative side effects.
I didn't found anything.
Closes #129.
=> Now cloning __props__ and changed order in 'with'

src/query/DomQuery.js, src/query/ExtenderHelper.js
Fixed the issues descriped in #132 and added ``observable._elements[].element`` in ``DomQuery.subscribeObservables()`` as some methods (e.g. ``blocks.observable([]).move()`` rely on it.
=> Fixed issues with the sort-extender described in #132.

src/query/Expression.js
Now observables with more then one expression on the same element (e.g. multiple attributes) will update all expression and not only the ont that got parsed first.
Fixes #138.
=> Fixed bug in observable._expressionKeys.

src/query/ChunkManager.js, src/query/DomQuery.js, src/query/VirtualElement.js, src/query/queries.js
I think I tested enough.
I will think about the tests mentioned in #111 and open an P.R. once I have a clean implementation.
Resolves #111.
=> Removed context.childs.

src/node/parseToVirtual.js
Just saw that this was not implemented and so comment queries (as all comments) did get removed and couldn't be executed server- and clientside.
Also added the missing "imports" in the define. Shouldn't make a difference yet. 
But maybe if (when) we change other modules.
=> Implemented Serverside comment query parsing.

src/mvc/Model.js
Missed that this also initializes collections and only moved it while testing something.
Totally my fault, sorry.
=> Reverted one change from #143 that broke collections.

lib/blocks/core.js, src/node/BrowserEnv.js, src/node/executePageScripts.js, src/node/findPageScripts.js
Let me first explain the problem:
I need to work with a  jsblocks project that uses [webpack](https://github.com/webpack/webpack) for bundling so all js is in one file. 
Webpack defines itself on the ``window`` object as a global, I added a ``with(window){}`` to the new Function call. I also added ``_blocks`` to the window object that contains the node-blocks instance and will be returned by the change in the jscore libary.
Feel free to ask questions if you have some.
Summary: 
Updated jscore to PR astoilkov/jscore#4.
Some external libaries (including module loaders and some code optimiziers (e.g. uglify)) rely on 'window' beeing the super-global, added 'with' statement in serverside rendering to satisfy that need.
Added property 'window._blocks' to serverside rendering context for the …
=> Better support for module loaders & libaries in serverside rendering.

build/tasks/debug.js, lib/blocks/core.js, lib/blocks/jsdebug.js, src/modules/Router.js, src/mvc/Application.js, src/mvc/Collection.js, src/mvc/Model.js, src/mvc/Property.js, src/mvc/bindContext.js, src/query/ElementsData.js, src/query/VirtualElement.js, src/query/extenders.js, src/query/observable.js
This is a huge PR because I had to fix some jsdoc and internal usage of functions, so that they don't throw errors.
Please take a look at the messages and diffs of the commits and not the whole diff.
The (imho) interesting commits are: 
https://github.com/astoilkov/jsblocks/commit/7f337f7eedd48fd4c1e7b28aa3abd87bd1e878b7
https://github.com/astoilkov/jsblocks/commit/fbb8831753d3bbddb2fed5978714833161c0d1ab
https://github.com/astoilkov/jsblocks/commit/666724987005175d9b39252987e22707010ad8d5
The other commits are mostly fixes of jsdoc params and internal usage of the methods that differ from the docs.  
This enables debug messages for normal methods (on param misuse, I'll implement custom errors from methods after this is merged).
I've tested it against the tests (only tests that misuse the …
=> Fixed / Implemented debug messages for "normal" methods.

build/tasks/debug.js, lib/blocks/jsdebug.js, src/.jshintrc, src/mvc/Application.js, src/query/DomQuery.js, src/query/Expression.js, src/query/observable.js
Added a ``blocks.debug.throwMessage(Message: String, [method:object], [level: String])`` function.
I don't like that we need to insert the 'method' object manualy if we wan't it to print usage.
Therefore the debug grunt tasks now inlines the Method object to a local variable ```__DEBUG_METHOD``.
I also don't like that because I had to add it to the .jshintrc, but I think it should fit until i come up with a better way (unless you have a better idea).
Also implemented that for failing async view initialization:
Array-observables that get reset with a non-nullish and non-array type: closes #116
And the usage of non comment-able data-queries on comments:
Also if you ever tried to add a brakepint to an expression you know that it's not that easy...
Now it is (at least in the debug build): …
```
=> Debugging enhancments (custom Messages and more )

.travis.yml, build/init.js, build/publish/GetClosedIssuesAndMergedPRs.graphql, build/publish/GetMasterCommits.graphql, build/publish/github-graphql.js, build/tasks/publish.js, package.json
With the graphql api it's possible to fetch everything we need.
The api is still early access/alpha and so has some bugs I needed to work arround and some things that don't work as smooth as I hoped. But that's okay.
Because it's an alpha version some things *could* go wrong with a release, but nothing I shouldn't be able to fix within a few minutes. So I guess that's fine.
GraphQL is nicer than normal REST APIs (previously I hit the limit of github api calls) and now it's maybe a couple dozen of calls instead of a couple hundred.
I would like it to have more options to query or to set vars within an query (SQL subselect-ish) but I guess it's a start.
Detection before it tries to publish anything:
- checks if ``GIT_KEY``, ``GIT_USER`` and ``GIT_EMAIL`` are set in the env.
- checks if the …
=> Travis releases
